### ISSUE TITLE
SIGABRT in rss.cpp:229

### ISSUE THREAD

**Issue by pietrushnic** [akrennmair/newsbeuter#146]
Problem occurs on master. Newsbeuter abort when trying to go to next unread message ('n' - key) during downloading  feeds from odesk.

gdb backtrace for all threads (securityToken removed):

```
Program received signal SIGABRT, Aborted.
0x00007ffff5b26407 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all where

Thread 6 (Thread 0x7ffff1385700 (LWP 4726)):
#0  0x00007ffff5bce50d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff76c53a3 in poll (__timeout=1000, __nfds=1, __fds=0x7fffe4033010) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  Curl_poll (ufds=0x7fffe4033010, nfds=1, timeout_ms=1000) at select.c:427
#3  0x00007ffff76bf8a2 in curl_multi_wait (multi_handle=multi_handle@entry=0x7fffe407b9f0, extra_fds=extra_fds@entry=0x0, extra_nfds=extra_nfds@entry=0, timeout_ms=<optimized out>, timeout_ms@entry=1000, 
    ret=ret@entry=0x7ffff1384448) at multi.c:889
#4  0x00007ffff76b8847 in easy_transfer (multi=0x7fffe407b9f0) at easy.c:681
#5  easy_perform (events=false, data=0x7fffe40008c0) at easy.c:797
#6  curl_easy_perform (easy=0x7fffe40008c0) at easy.c:816
#7  0x00000000004de5de in rsspp::parser::parse_url (this=0x7ffff1384620, 
    url="https://www.odesk.com/find-work-home/rss/?topic=463731&securityToken=xxx~xx", lastmodified=0, etag="", api=0x0, cookie_cache="", 
    ehandle=0x7fffe40008c0) at rss/parser.cpp:132
#8  0x000000000046f12a in newsbeuter::rss_parser::download_http (this=0x7ffff1384980, 
    uri="https://www.odesk.com/find-work-home/rss/?topic=463731&securityToken=xxx~xx") at src/rss_parser.cpp:165
#9  0x000000000046e81b in newsbeuter::rss_parser::retrieve_uri (this=0x7ffff1384980, 
    uri="https://www.odesk.com/find-work-home/rss/?topic=463731&securityToken=xxx~xx") at src/rss_parser.cpp:127
#10 0x000000000046df6a in newsbeuter::rss_parser::parse (this=0x7ffff1384980) at src/rss_parser.cpp:36
#11 0x0000000000443946 in newsbeuter::controller::reload (this=0x7fffffffde80, pos=5, max=43, unattended=false, easyhandle=0x7ffff1384c50) at src/controller.cpp:722
#12 0x0000000000444c44 in newsbeuter::controller::reload_range (this=0x7fffffffde80, start=0, end=42, size=43, unattended=false) at src/controller.cpp:844
#13 0x0000000000444ead in newsbeuter::controller::reload_all (this=0x7fffffffde80, unattended=false) at src/controller.cpp:876
#14 0x000000000045a6c9 in newsbeuter::downloadthread::run (this=0x93ba30) at src/downloadthread.cpp:24
#15 0x00000000004d62d7 in newsbeuter::run_thread (p=0x93ba30) at src/thread.cpp:45
#16 0x00007ffff7bc70a4 in start_thread (arg=0x7ffff1385700) at pthread_create.c:309
#17 0x00007ffff5bd704d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7ffff1b86700 (LWP 4454)):
#0  0x00007ffff5ba88bd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff5ba8754 in __sleep (seconds=0) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x0000000000457cb5 in newsbeuter::reloadthread::run (this=0xa6dee0) at src/reloadthread.cpp:40
#3  0x00000000004d62d7 in newsbeuter::run_thread (p=0xa6dee0) at src/thread.cpp:45
#4  0x00007ffff7bc70a4 in start_thread (arg=0x7ffff1b86700) at pthread_create.c:309
#5  0x00007ffff5bd704d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ffff7fcc740 (LWP 4453)):
#0  0x00007ffff5b26407 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5b277e8 in __GI_abort () at abort.c:89
#2  0x000000000045d295 in newsbeuter::rss_feed::get_item_by_guid_unlocked (this=0x7fffe40a4440, 
    guid="https://www.odesk.com/jobs/Raspberry-submodule-breadboard-and-python-driver-code_%7E0159450ba080ec7a38?source=rss") at src/rss.cpp:229
#3  0x000000000045d0f1 in newsbeuter::rss_feed::get_item_by_guid (this=0x7fffe40a4440, guid="https://www.odesk.com/jobs/Raspberry-submodule-breadboard-and-python-driver-code_%7E0159450ba080ec7a38?source=rss")
    at src/rss.cpp:215
#4  0x0000000000495a5b in newsbeuter::itemview_formaction::process_operation (this=0x8f82d0, op=newsbeuter::OP_NEXTUNREAD, automatic=false, args=0x0) at src/itemview_formaction.cpp:154
#5  0x0000000000476774 in newsbeuter::formaction::process_op (this=0x8f82d0, op=newsbeuter::OP_NEXTUNREAD, automatic=false, args=0x0) at src/formaction.cpp:139
#6  0x000000000042d0c6 in newsbeuter::view::run (this=0x7fffffffdd50) at src/view.cpp:239
#7  0x0000000000441f64 in newsbeuter::controller::run (this=0x7fffffffde80, argc=1, argv=0x7fffffffe288) at src/controller.cpp:608
#8  0x00000000004086cb in main (argc=1, argv=0x7fffffffe288) at newsbeuter.cpp:30
```

Let me know how I can help solve this issue. It is annoying because I cannot walk through new feeds when downloading is in progress.

**Comment by Minoru** [comment]
StackOverflow [describes](http://stackoverflow.com/questions/33777880/sigabrt-in-raise-c) similar symptoms and suggests that ABI mismatch might be the case. Can you ensure that the compiler used by your distribution is very same that you're using to build Newsbeuter?
