### ISSUE TITLE
segmentation fault on podcasts downloads

### ISSUE THREAD

**Issue by o-ze** [akrennmair/newsbeuter#167]
When using podbeuter to download enqueued podcasts streams, I get this error as an output
25953 segmentation fault (core dumped)  podbeuterd

**Comment by logenkain** [comment]
I can second this.  I've been having this issue since the new release.  As a result, I haven't listened to podcasts since this release.

**Comment by o-ze** [comment]
Thanks logenkain, I downgraded the package to "newsbeuter-2.8-1-x86_64" and everything is working well.

**Comment by arvedarved** [comment]
backtrace:
```
(gdb) where
#0  0x0000000802cbe6ca in thr_kill () from /lib/libc.so.7
#1  0x0000000802d93149 in abort () from /lib/libc.so.7
#2  0x000000080238ab81 in std::__1::thread::~thread () from /usr/lib/libc++.so.1
#3  0x0000000000411aff in podbeuter::pb_controller::start_downloads (this=0x7fffffffe928) at src/pb_controller.cpp:290
#4  0x00000000004185fa in podbeuter::pb_view::run (this=0x7fffffffe8f8, auto_download=true) at src/pb_view.cpp:75
#5  0x000000000041106e in podbeuter::pb_controller::run (this=0x7fffffffe928, argc=1, argv=0x7fffffffea98)
    at src/pb_controller.cpp:227
#6  0x0000000000406f7b in main (argc=1, argv=0x7fffffffea98) at podbeuter.cpp:26
(gdb)
```

**Comment by louipc** [comment]
Those patches work for me.
