### ISSUE TITLE
Segfault while updating feeds

### ISSUE THREAD

**Issue by gregf** [akrennmair/newsbeuter#190]
```
(gdb) backtrace
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
#1  0x00007ffff51c427f in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#2  0x00007ffff51c4179 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#3  0x00007ffff5147bfa in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#4  0x00007ffff51b0ee2 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#5  0x00007ffff51b8b7a in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#6  0x00007ffff51382c2 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#7  0x00007ffff51343d8 in gnutls_handshake () from /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28
#8  0x00007ffff76d387f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#9  0x00007ffff76d4b9c in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#10 0x00007ffff76d5820 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#11 0x00007ffff76901ce in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#12 0x00007ffff76b3cd6 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#13 0x00007ffff76b4d96 in curl_multi_perform () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#14 0x00007ffff76abc1b in curl_easy_perform () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#15 0x0000555555659f92 in ?? ()
#16 0x000000005554f852 in ?? ()
#17 0x00007fffe3ffe900 in ?? ()
#18 0x00007fffe3ffea30 in ?? ()
#19 0x00007fffe3ffe930 in ?? ()
#20 0x00007fffffffcc58 in ?? ()
#21 0x00007fffe3ffe930 in ?? ()
#22 0x00007ffff6a9ebd8 in std::string::_Rep::_S_empty_rep_storage () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x148a208f9be12d00 in ?? ()
#24 0x00007fffd457d7a8 in ?? ()
#25 0x00007fffffffcc58 in ?? ()
#26 0x00007fffe3ffea50 in ?? ()
#27 0x00007fffe3ffe930 in ?? ()
#28 0x0000000000000000 in ?? ()
(gdb)
```

**Comment by h3xx** [comment]
Can you provide more information? Such as:
* What were you doing when you saw this error?
* What is your list of feeds
* Can you reproduce the error given the same feeds?

**Comment by gregf** [comment]
This happened to me for about a day and has since gone away so I can no longer reproduce it.
