### ISSUE TITLE
Segmentation fault with newsbeuter 2.7 on OpenBSD 5.6

### ISSUE THREAD

**Issue by lorenzog** [akrennmair/newsbeuter#197]
Running newsbeuter from OpenBSD 5.6 results in a segmentation fault.
Steps:
 1. run `newsbeuter`
 2. press 'r' on a feed to refresh
 3. Segmentation fault:

```gdb
    Program received signal SIGSEGV, Segmentation fault.
    0x057e6d0e in sqlite3VXPrintf (pAccum=0xcfbed494, bFlags=0, fmt=0x3608738a "q','%q',%d, '%q')",
        ap=0xcfbed580 ",�\020#,�\020#") at /usr/src/lib/libsqlite3/src/printf.c:670
    670             for(i=n=0; k!=0 && (ch=escarg[i])!=0; i++, k--){
    Current language:  auto; currently c

    (gdb) where
    #0  0x057e6d0e in sqlite3VXPrintf (pAccum=0xcfbed494, bFlags=0, fmt=0x3608738a "q','%q',%d, '%q')",
        ap=0xcfbed580 ",�\020#,�\020#") at /usr/src/lib/libsqlite3/src/printf.c:670
    #1  0x057e7dfd in sqlite3_vmprintf (
        zFormat=0x360872e0 "INSERT INTO rss_item (guid,title,author,url,feedurl,pubDate,content,unread,enclosure_url,enclosure_type,enqueued, base) VALUES ('%q','%q','%q','%q','%q','%u','%q','%d','%q','%q',%d, '%q')", ap=0xcfbed55c "�]�}�\235M~,�\020#\f�e\201\214�M~\017I�U")
        at /usr/src/lib/libsqlite3/src/printf.c:928
    #2  0x16092a28 in newsbeuter::cache::prepare_query (this=0x7babdbf0, 
        format=0x360872e0 "INSERT INTO rss_item (guid,title,author,url,feedurl,pubDate,content,unread,enclosure_url,enclosure_type,enqueued, base) VALUES ('%q','%q','%q','%q','%q','%u','%q','%d','%q','%q',%d, '%q')") at src/cache.cpp:775
    #3  0x16095e22 in newsbeuter::cache::update_rssitem_unlocked (this=0x7babdbf0, item=@0xcfbed748, 
        feedurl=@0x7e4db1a0, reset_unread=false) at src/cache.cpp:649
    #4  0x16099651 in newsbeuter::cache::externalize_rssfeed (this=0x7babdbf0, feed=@0xcfbed810, 
        reset_unread=false) at src/cache.cpp:388
    #5  0x160d0d18 in newsbeuter::controller::save_feed (this=0xcfbee198, feed=@0xcfbed930, pos=0)
        at src/controller.cpp:1390
    #6  0x160d3d08 in newsbeuter::controller::reload (this=0xcfbee198, pos=0, max=0, unattended=false, 
        easyhandle=0x0) at src/controller.cpp:712
    #7  0x1612bc1f in newsbeuter::feedlist_formaction::process_operation (this=0x7f070a00, h ?:Help
        op=newsbeuter::OP_RELOAD, automatic=false, args=0x0) at src/feedlist_formaction.cpp:107
    #8  0x16119e54 in newsbeuter::formaction::process_op (this=0x7f070a00, op=newsbeuter::OP_RELOAD,
        automatic=false, args=0x0) at src/formaction.cpp:139
    #9  0x160c6096 in newsbeuter::view::run (this=0xcfbee300) at src/view.cpp:239
    #10 0x160d7005 in newsbeuter::controller::run (this=0xcfbee198, argc=1, argv=0xcfbee404)
        at src/controller.cpp:595
    #11 0x1609111e in main (argc=1, argv=0xcfbee404) at newsbeuter.cpp:30
```
Same behaviour happens when running `newsbeuter -r` and pressing 'r' to refresh a feed.

**Comment by lorenzog** [comment]
Issue also shows up in OpenBSD 5.7 (i386 flavour) but not on 5.7 (amd64).
